sudo: false
language: node_js
node_js:
    - 14
branches:
    only:
        - main
        - develop
        - /^\d+\.\d+(\.(\d+|x))?(-\S*)?$/
install:
    - npm install
script:
    - npm run pretty:check
    - npm run lint
    - npm run build
    - npm run test
    - codecov -f coverage/*.json
