/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_cognito_identity_pool_id:
        'us-east-1:7fce7cc9-9e8a-427f-9143-a22eb3319b87',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_9oT3kONBL',
    aws_user_pools_web_client_id: '6njsmi65nnhs486gjjue644caf',
    oauth: {
        domain:
            'lionster0192a0c6-0192a0c6-dev.auth.us-east-1.amazoncognito.com',
        scope: [
            'phone',
            'email',
            'openid',
            'profile',
            'aws.cognito.signin.user.admin'
        ],
        redirectSignIn: 'http://localhost:3000/users/redirect/login/',
        redirectSignOut: 'http://localhost:3000/users/redirect/logout/',
        responseType: 'code'
    },
    federationTarget: 'COGNITO_USER_POOLS'
};

export default awsmobile;
