/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_cognito_identity_pool_id:
        'us-east-1:7c78962b-d3d0-4bf7-846f-74d4264e7694',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_IzZe2dOAO',
    aws_user_pools_web_client_id: 'frbilp7cgu8athgb3357kaa8r',
    oauth: {
        domain:
            'lionster0192a0c6-0192a0c6-dev.auth.us-east-1.amazoncognito.com',
        scope: [
            'phone',
            'email',
            'openid',
            'profile',
            'aws.cognito.signin.user.admin'
        ],
        redirectSignIn: 'http://localhost:3000/users/redirect/login/',
        redirectSignOut: 'http://localhost:3000/users/redirect/logout/',
        responseType: 'code'
    },
    federationTarget: 'COGNITO_USER_POOLS'
};

export default awsmobile;
