/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_cognito_identity_pool_id:
        'us-east-1:42b21d62-2907-4124-a0cc-1cb7bf5a54a9',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_IPiLAbWG6',
    aws_user_pools_web_client_id: '313s58p25m9aeuj232c33ug3ot',
    oauth: {
        domain:
            'lionster0192a0c6-0192a0c6-dev.auth.us-east-1.amazoncognito.com',
        scope: [
            'phone',
            'email',
            'openid',
            'profile',
            'aws.cognito.signin.user.admin'
        ],
        redirectSignIn: 'http://localhost:3000/users/redirect/login/',
        redirectSignOut: 'http://localhost:3000/users/redirect/logout/',
        responseType: 'code'
    },
    federationTarget: 'COGNITO_USER_POOLS'
};

export default awsmobile;
